@ECHO OFF

move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\Hoxton House 1953-54 Catalogue.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyHoxton House 1953-54 Catalogue.jpg"
move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\WrestlingTeam1952.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyWrestlingTeam1952.jpg"
move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\Stewart Gym 1953-54 Catalogue.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyStewart Gym 1953-54 Catalogue.jpg"
move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\Chronicle April 1954 Wrestling.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyChronicle April 1954 Wrestling.jpg"
move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\Pendleton Exterior 1953-54 Catalogue.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyPendleton Exterior 1953-54 Catalogue.jpg"
move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\Health Center 1953-54 Catalogue.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyHealth Center 1953-54 Catalogue.jpg"
move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\Centennial Gym 1953-54 Catalogue.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyCentennial Gym 1953-54 Catalogue.jpg"
move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\Bryan Library 1953-54 Catalogue.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyBryan Library 1953-54 Catalogue.jpg"
move "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\Preservation Files\ms_cm_mss_409_939\Photos\mccain hs pics\Wrestling1953.jpg" "\\libfile.lib.asu.edu\share\Archivematica\ms_cm_mss_409\WorkingDirectory\Final_HeirarchyWrestling1953.jpg"